version: '3'

services:
  n8n:
    build: .
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=votre_clef_de_chiffrement
      - WEBHOOK_URL=https://votre-domaine.com
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=https
      - N8N_PATH=/
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local 